#!/bin/bash

#This script was developed and is maintained by Kevin Chevreuil - Kaisen for Kaisen Linux project
#and is under AGPL license.

set -e

export DEBIAN_FRONTEND=noninteractive

YELLOW='\e[0;33m'
GREEN='\e[1;32m'
RED='\e[1;31m'

#Check root execution
if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this screen as root or with sudo command to continue."
        exit 1
fi

if [[ "$EUID" -eq "0" ]]; then
	echo -e $GREEN "Check APT access..."
	tput init;apt update 2>&1 | grep '^[WE]:' && echo -e $RED "Please check your internet connection or APT access to continue." && exit 1
	echo ""
	echo -e $GREEN "APT access ok, check connected network interface..."
	echo ""
	tput init;ip route get 8.8.8.8 | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}' | grep '^[w]l' 1> /dev/null && echo -e $RED "Disable wifi and connect an Ethernet cable or USB modem to continue." && exit 1
	echo -e $GREEN "Check if new kaisen-interface-switcher version exist..."
        echo ""
	tput init;apt install -y kaisen-kde
	echo ""
	echo -e $GREEN "Welcome at Kaisen Linux interface switcher (KDE version)."
	echo ""
	echo -e $GREEN "This script will install a graphical interface of your choice listed below."
	echo ""
	echo -e $YELLOW "CAUTION: This script will automatically restart the computer at the end of the process."
	echo -e $YELLOW "Your unsaved work will be lost."
	echo ""
	echo -e $GREEN "Which graphical interface do you want to install?"
	echo ""
	echo -e $GREEN "   1) XFCE"
	echo -e $GREEN "   2) LXDE"
	echo -e $GREEN "   3) MATE"
	echo -e $GREEN "   4) EXIT"
	echo ""

	while [[ $OPTION != "1" && $OPTION != "2" && $OPTION != "3" && $OPTION != "4" ]]; do
		read -rp "Select an option [1-4]: " OPTION
	done
	echo ""

if [[ $OPTION = "1" ]]; then
	echo -e $GREEN "XFCE installation..."
	echo "";tput init; \
	apt autoremove -y `dpkg -l | grep kde | cut -d \  -f 3` && apt install -y kaisen-xfce || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on XFCE, reapplying XFCE users configurations or reapplying XFCE configurations
	for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/XFCE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{xfce4,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
	systemctl restart lightdm
fi

if [[ $OPTION = "2" ]]; then
	echo -e $GREEN "LXDE installation..."
        echo "";tput init; \
	apt autoremove -y `dpkg -l | grep kde | cut -d \  -f 3` && apt install -y kaisen-lxde || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on LXDE, reapplying LXDE users configurations or reapplying LXDE configurations
	for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/LXDE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{lxpanel,lxsession,lxterminal,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
	systemctl restart lightdm
fi

if [[ $OPTION = "3" ]]; then
	echo -e $GREEN "MATE installation..."
        echo "";tput init; \
	apt autoremove -y `dpkg -l | grep kde | cut -d \  -f 3` && apt install -y kaisen-mate || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on MATE, reapplying MATE users configurations or reapplying MATE configurations
	for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/MATE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{dconf,mate,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
	systemctl restart lightdm
fi

if [[ $OPTION = "4" ]]; then
	exit 0
fi
fi
