#!/bin/bash

#This script was developed and is maintained by Kevin Chevreuil - Kaisen for Kaisen Linux project
#and is under AGPL license.

set -e

export DEBIAN_FRONTEND=noninteractive

YELLOW='\e[0;33m'
GREEN='\e[1;32m'
RED='\e[1;31m'

#Check root execution
if [[ "$EUID" -ne "0" ]]; then
	echo -e $RED "Run this screen as root or with sudo command to continue."
	exit 1
fi

if [[ "$EUID" -eq "0" ]]; then
	echo -e $GREEN "Check APT access..."
	tput init;apt update 2>&1 | grep '^[WE]:' && echo -e $RED "Please check your internet connection to continue." && exit 1
	echo ""
	echo -e $GREEN "APT access ok, check to update kaisen-interface-switcher..."
	echo ""
	tput init;apt install -y kaisen-xfce
	echo -e $GREEN "Welcome at Kaisen Linux interface switcher (XFCE version)."
	echo ""
	echo -e $GREEN "This script will install a graphical interface of your choice listed below."
	echo ""
	echo -e $YELLOW "CAUTION: This script will automatically restart display manager or your computer will restart at the end of the process."
	echo -e $YELLOW "Your unsaved work will be lost."
	echo ""
	echo -e $GREEN "Which graphical interface do you want to install?"
	echo ""
	echo -e $GREEN "   1) KDE"
	echo -e $GREEN "   2) LXDE"
	echo -e $GREEN "   3) MATE"
	echo -e $GREEN "   4) EXIT"
	echo ""
	while [[ $OPTION != "1" && $OPTION != "2" && $OPTION != "3" && $OPTION != "4" ]]; do
		read -rp "Select an option [1-4]: " OPTION
	done
	echo ""

if [[ $OPTION = "1" ]]; then
	echo -e $GREEN "KDE installation..."
	echo "";tput init; \
	apt update;apt remove --fix-missing -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
	firefox-l10n-pt-pt fonts-cantarell fonts-powerline gnome-accessibility-themes gnome-themes-extra \
	gnome-themes-extra-data gtk2-engines-pixbuf hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libcanberra-gtk3-0 \
	libcanberra-gtk3-module libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 libgarcon-common libgarcon-gtk3-1-0 \
	libjs-sphinxdoc libjs-underscore liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
	libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
	libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
	light-locker lightdm lightdm-gtk-greeter mobile-broadband-provider-info network-manager network-manager-gnome \
	pavucontrol python-configparser python-entrypoints python-keyring tango-icon-theme thunar thunar-data thunar-volman \
	tumbler tumbler-common x11-apps x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel \
	xfce4-power-manager xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter \
	xfce4-session xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi \
	xfonts-scalable xfwm4 xiccd xinit xorg xorg-docs-core;apt -y --fix-broken install;apt install -y kaisen-kde; \
	apt -y --fix-broken install;apt -y autoremove;/sbin/reboot
fi

if [[ $OPTION = "2" ]]; then
	echo -e $GREEN "LXDE installation..."
        echo "";tput init; \
        apt update;apt remove --fix-missing -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
        firefox-l10n-pt-pt fonts-cantarell fonts-powerline gnome-accessibility-themes gnome-themes-extra \
        gnome-themes-extra-data gtk2-engines-pixbuf hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libcanberra-gtk3-0 \
        libcanberra-gtk3-module libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 libgarcon-common libgarcon-gtk3-1-0 \
        libjs-sphinxdoc libjs-underscore liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
        libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
        libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
        light-locker lightdm lightdm-gtk-greeter mobile-broadband-provider-info network-manager network-manager-gnome \
        pavucontrol python-configparser python-entrypoints python-keyring tango-icon-theme thunar thunar-data thunar-volman \
        tumbler tumbler-common x11-apps x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel \
        xfce4-power-manager xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter \
        xfce4-session xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi \
        xfonts-scalable xfwm4 xiccd xinit xorg xorg-docs-core;apt -y --fix-broken install;apt install -y kaisen-lxde; \
        apt -y --fix-broken install;apt -y autoremove;systemctl restart lightdm
fi

if [[ $OPTION = "3" ]]; then
	echo -e $GREEN "MATE installation..."
        echo "";tput init; \
        apt update;apt remove --fix-missing -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
        firefox-l10n-pt-pt fonts-cantarell fonts-powerline gnome-accessibility-themes gnome-themes-extra \
        gnome-themes-extra-data gtk2-engines-pixbuf hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libcanberra-gtk3-0 \
        libcanberra-gtk3-module libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 libgarcon-common libgarcon-gtk3-1-0 \
        libjs-sphinxdoc libjs-underscore liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
        libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
        libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
        light-locker lightdm lightdm-gtk-greeter mobile-broadband-provider-info network-manager network-manager-gnome \
        pavucontrol python-configparser python-entrypoints python-keyring tango-icon-theme thunar thunar-data thunar-volman \
        tumbler tumbler-common x11-apps x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel \
        xfce4-power-manager xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter \
        xfce4-session xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi \
        xfonts-scalable xfwm4 xiccd xinit xorg xorg-docs-core;apt -y --fix-broken install;apt install -y kaisen-mate; \
        apt -y --fix-broken install;apt -y autoremove;systemctl restart lightdm
fi

if [[ $OPTION = "4" ]]; then
	exit 0
fi

fi
