#!/bin/bash

#This script was developed and is maintained by Kevin Chevreuil - Kaisen for Kaisen Linux project
#and is under AGPL license.

set -e

export DEBIAN_FRONTEND=noninteractive

YELLOW='\e[0;33m'
GREEN='\e[1;32m'
RED='\e[1;31m'

#Check root execution
if [[ "$EUID" -ne "0" ]]; then
	echo -e $RED "Run this screen as root or with sudo command to continue."
	exit 1
fi

if [[ "$EUID" -eq "0" ]]; then
	echo -e $GREEN "Check APT access..."
	tput init;apt update 2>&1 | grep '^[WE]:' && echo -e $RED "Please check your internet connection or APT access to continue." && exit 1
	echo ""
	echo -e $GREEN "APT access ok, check connected network interface..."
	echo ""
	tput init;ip route get 8.8.8.8 | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}' | grep '^[w]l' 1> /dev/null && echo -e $RED "Disable wifi and connect an Ethernet cable or USB modem to continue." && exit 1
	echo -e $GREEN "Check if new kaisen-interface-switcher version exist..."
        echo ""
	tput init;apt install -y kaisen-xfce
	echo ""
	echo -e $GREEN "Welcome at Kaisen Linux interface switcher (XFCE version)."
	echo ""
	echo -e $GREEN "This script will install a graphical interface of your choice listed below."
	echo ""
	echo -e $YELLOW "CAUTION: This script will automatically restart display manager or your computer will restart at the end of the process."
	echo -e $YELLOW "Your unsaved work will be lost."
	echo ""
	echo -e $GREEN "Which graphical interface do you want to install?"
	echo ""
	echo -e $GREEN "   1) KDE"
	echo -e $GREEN "   2) LXDE"
	echo -e $GREEN "   3) MATE"
	echo -e $GREEN "   4) EXIT"
	echo ""
	while [[ $OPTION != "1" && $OPTION != "2" && $OPTION != "3" && $OPTION != "4" ]]; do
		read -rp "Select an option [1-4]: " OPTION
	done
	echo ""

case $OPTION in
	1|2|3)
	for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
	mkdir -p /usr/share/kaisen-interface-switcher/$users/XFCE 2> /dev/null || true && cp -rp /home/$users/.config/{xfce4,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /usr/share/kaisen-interface-switcher/$users/XFCE 2> /dev/null || true
	done
	;;
esac

if [[ $OPTION = "1" ]]; then
	echo -e $GREEN "KDE installation..."
	echo "";tput init; \
	apt remove -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it firefox-l10n-pt-pt \
	fonts-powerline gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines-pixbuf \
	hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 \
	libgarcon-common libgarcon-gtk3-1-0 liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
	libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
	libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
	light-locker lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings mobile-broadband-provider-info network-manager \
	network-manager-gnome pavucontrol tango-icon-theme thunar thunar-data thunar-volman tumbler tumbler-common x11-apps \
	x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel xfce4-power-manager \
	xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-session \
	xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi xfonts-scalable xfwm4 \
	xiccd xinit xorg xorg-docs-core && \
	apt install -y kaisen-kde || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on KDE, reapplying KDE users configurations or reapplying default KDE configurations
        for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/KDE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
	if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "2" ]]; then
	echo -e $GREEN "LXDE installation..."
	echo "";tput init; \
	apt remove -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it firefox-l10n-pt-pt \
        fonts-powerline gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines-pixbuf \
        hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 \
        libgarcon-common libgarcon-gtk3-1-0 liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
        libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
        libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
        light-locker lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings mobile-broadband-provider-info network-manager \
        network-manager-gnome pavucontrol tango-icon-theme thunar thunar-data thunar-volman tumbler tumbler-common x11-apps \
        x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel xfce4-power-manager \
        xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-session \
        xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi xfonts-scalable xfwm4 \
        xiccd xinit xorg xorg-docs-core && \
	apt install -y kaisen-lxde || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on LXDE, reapplying LXDE users configurations or reapplying default LXDE configurations
        for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/LXDE/* /home/$users/.config/ 2> /dev/null || cp -rp /etc/skel/.config/{lxpanel,lxsession,lxterminal,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
        if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "3" ]]; then
	echo -e $GREEN "MATE installation..."
	echo "";tput init; \
	apt remove -y exo-utils firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it firefox-l10n-pt-pt \
        fonts-powerline gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines-pixbuf \
        hunspell-fr kaisen-menu kaisen-skeleton kaisen-xfce libexo-2-0 libexo-common libexo-helpers libgarcon-1-0 \
        libgarcon-common libgarcon-gtk3-1-0 liblightdm-gobject-1-0 libndp0 libnma-common libnma0 libteamdctl0 libthunarx-3-0 \
        libtumbler-1-0 libwnck-3-0 libwnck-3-common libxfce4panel-2.0-4 libxfce4ui-1-0 libxfce4ui-2-0 libxfce4ui-common \
        libxfce4ui-utils libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-3 libxklavier16 libxpresent1 \
        light-locker lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings mobile-broadband-provider-info network-manager \
        network-manager-gnome pavucontrol tango-icon-theme thunar thunar-data thunar-volman tumbler tumbler-common x11-apps \
        x11-session-utils xcursor-themes xfce4 xfce4-appfinder xfce4-notifyd xfce4-panel xfce4-power-manager \
        xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-session \
        xfce4-settings xfce4-terminal xfconf xfdesktop4 xfdesktop4-data xfonts-100dpi xfonts-75dpi xfonts-scalable xfwm4 \
        xiccd xinit xorg xorg-docs-core && \
	apt install -y kaisen-mate || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on MATE, reapplying MATE users configurations or reapplying default MATE configurations
        for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/MATE/* /home/$users/.config/ 2> /dev/null || cp -rp /etc/skel/.config/{dconf,mate,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
        if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "4" ]]; then
	exit 0
fi

fi
