#!/bin/bash

#This script was developed and is maintained by Kevin Chevreuil - Kaisen for Kaisen Linux project
#and is under AGPL license.

set -e

export DEBIAN_FRONTEND=noninteractive

YELLOW='\e[0;33m'
GREEN='\e[1;32m'
RED='\e[1;31m'

#Check root execution
if [[ "$EUID" -ne "0" ]]; then
	echo -e $RED "Run this screen as root or with sudo command to continue."
	exit 1
fi

if [[ "$EUID" -eq "0" ]]; then
	echo -e $GREEN "Check APT access..."
	tput init;apt update 2>&1 | grep '^[WE]:' && echo -e $RED "Please check your internet connection or APT access to continue." && exit 1
	echo ""
	echo -e $GREEN "APT access ok, check connected network interface..."
	echo ""
	tput init;ip route get 8.8.8.8 | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}' | grep '^[w]l' 1> /dev/null && echo -e $RED "Disable wifi and connect an Ethernet cable or USB modem to continue." && exit 1
	echo -e $GREEN "Check if new kaisen-interface-switcher version exist..."
        echo ""
	tput init;apt install -y kaisen-mate
	echo ""
	echo -e $GREEN "Welcome at Kaisen Linux interface switcher (MATE version)."
	echo ""
	echo -e $GREEN "This script will install a graphical interface of your choice listed below."
	echo ""
	echo -e $YELLOW "CAUTION: This script will automatically restart display manager or your computer will restart at the end of the process."
	echo -e $YELLOW "Your unsaved work will be lost."
	echo ""
	echo -e $GREEN "Which graphical interface do you want to install?"
	echo ""
	echo -e $GREEN "   1) KDE"
	echo -e $GREEN "   2) LXDE"
	echo -e $GREEN "   3) XFCE"
	echo -e $GREEN "   4) EXIT"
	echo ""

	while [[ $OPTION != "1" && $OPTION != "2" && $OPTION != "3" && $OPTION != "4" ]]; do
		read -rp "Select an option [1-4]: " OPTION
	done
	echo ""

case $OPTION in
	1|2|3)
	for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        mkdir -p /usr/share/kaisen-interface-switcher/$users/MATE 2> /dev/null || true && cp -rp /home/$users/.config/{dconf,mate,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /usr/share/kaisen-interface-switcher/$users/MATE 2> /dev/null || true
        done
	;;
esac

if [[ $OPTION = "1" ]]; then
	echo -e $GREEN "KDE installation..."
	echo "";tput init; \
	apt remove -y atril atril-common caja caja-common conky-all conkycolors debian-mate-default-settings engrampa \
	engrampa-common eom eom-common ffmpegthumbnailer firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
	firefox-l10n-pt-pt fonts-mathjax fonts-powerline gir1.2-eom-1.0 gir1.2-gtksource-3.0 gir1.2-matemenu-2.0 \
	gir1.2-peas-1.0 gir1.2-pluma-1.0 gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines \
	gtk2-engines-murrine gtk2-engines-pixbuf hunspell-fr kaisen-mate kaisen-menu kaisen-skeleton libatrildocument3 \
	libatrilview3 libaudclient2 libcaja-extension1 libcpupower1 libexempi8 libffmpegthumbnailer4v5 libgail-3-0 \
	libgtk-layer-shell0 libgtksourceview-3.0-1 libgtksourceview-3.0-common libgucharmap-2-90-7 libid3tag0 libimlib2 \
	libjs-mathjax liblightdm-gobject-1-0 liblua5.1-0 libmarco-private2 libmate-desktop-2-17 libmate-menu2 \
	libmate-panel-applet-4-1 libmate-slab0 libmate-window-settings1 libmatedict6 libmatekbd-common libmatekbd4 \
	libmatemixer-common libmatemixer0 libmateweather-common libmateweather1 libndp0 libnma-common libnma0 libpeas-1.0-0 \
	libpeas-common librda-common librda0 libteamdctl0 libwnck-3-0 libwnck-3-common libxklavier16 libxmmsclient6 \
	libxpresent1 lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings marco marco-common mate-applet-brisk-menu \
	mate-applets mate-applets-common mate-backgrounds mate-calc mate-calc-common mate-control-center \
	mate-control-center-common mate-desktop mate-desktop-common mate-desktop-environment mate-desktop-environment-core \
	mate-icon-theme mate-media mate-media-common mate-menus mate-notification-daemon mate-notification-daemon-common \
	mate-panel mate-panel-common mate-polkit mate-polkit-common mate-power-manager mate-power-manager-common \
	mate-screensaver mate-screensaver-common mate-session-manager mate-settings-daemon mate-settings-daemon-common \
	mate-system-monitor mate-system-monitor-common mate-terminal mate-terminal-common mate-themes mate-user-guide \
	mate-utils mate-utils-common menu-xdg mobile-broadband-provider-info network-manager network-manager-gnome pluma \
	pluma-common python-configparser python-entrypoints python-keyring xcursor-themes zenity zenity-common && \
	apt install -y kaisen-kde || true && apt -y --fix-broken install && apt -y autoremove
	if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "2" ]]; then
	echo -e $GREEN "LXDE installation..."
	echo "";tput init; \
	apt remove -y atril atril-common caja caja-common conky-all conkycolors debian-mate-default-settings engrampa \
        engrampa-common eom eom-common ffmpegthumbnailer firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
        firefox-l10n-pt-pt fonts-mathjax fonts-powerline gir1.2-eom-1.0 gir1.2-gtksource-3.0 gir1.2-matemenu-2.0 \
        gir1.2-peas-1.0 gir1.2-pluma-1.0 gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines \
        gtk2-engines-murrine gtk2-engines-pixbuf hunspell-fr kaisen-mate kaisen-menu kaisen-skeleton libatrildocument3 \
        libatrilview3 libaudclient2 libcaja-extension1 libcpupower1 libexempi8 libffmpegthumbnailer4v5 libgail-3-0 \
        libgtk-layer-shell0 libgtksourceview-3.0-1 libgtksourceview-3.0-common libgucharmap-2-90-7 libid3tag0 libimlib2 \
        libjs-mathjax liblightdm-gobject-1-0 liblua5.1-0 libmarco-private2 libmate-desktop-2-17 libmate-menu2 \
        libmate-panel-applet-4-1 libmate-slab0 libmate-window-settings1 libmatedict6 libmatekbd-common libmatekbd4 \
        libmatemixer-common libmatemixer0 libmateweather-common libmateweather1 libndp0 libnma-common libnma0 libpeas-1.0-0 \
        libpeas-common librda-common librda0 libteamdctl0 libwnck-3-0 libwnck-3-common libxklavier16 libxmmsclient6 \
        libxpresent1 lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings marco marco-common mate-applet-brisk-menu \
        mate-applets mate-applets-common mate-backgrounds mate-calc mate-calc-common mate-control-center \
        mate-control-center-common mate-desktop mate-desktop-common mate-desktop-environment mate-desktop-environment-core \
        mate-icon-theme mate-media mate-media-common mate-menus mate-notification-daemon mate-notification-daemon-common \
        mate-panel mate-panel-common mate-polkit mate-polkit-common mate-power-manager mate-power-manager-common \
        mate-screensaver mate-screensaver-common mate-session-manager mate-settings-daemon mate-settings-daemon-common \
        mate-system-monitor mate-system-monitor-common mate-terminal mate-terminal-common mate-themes mate-user-guide \
        mate-utils mate-utils-common menu-xdg mobile-broadband-provider-info network-manager network-manager-gnome pluma \
        pluma-common python-configparser python-entrypoints python-keyring xcursor-themes zenity zenity-common && \
	apt install -y kaisen-lxde || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on LXDE, reapplying LXDE users configurations or reapplying default LXDE configurations
        for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/LXDE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{lxpanel,lxsession,lxterminal,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
        if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "3" ]]; then
	echo -e $GREEN "XFCE installation..."
	echo "";tput init; \
	apt remove -y atril atril-common caja caja-common conky-all conkycolors debian-mate-default-settings engrampa \
        engrampa-common eom eom-common ffmpegthumbnailer firefox-l10n-de firefox-l10n-es-es firefox-l10n-fr firefox-l10n-it \
        firefox-l10n-pt-pt fonts-mathjax fonts-powerline gir1.2-eom-1.0 gir1.2-gtksource-3.0 gir1.2-matemenu-2.0 \
        gir1.2-peas-1.0 gir1.2-pluma-1.0 gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data gtk2-engines \
        gtk2-engines-murrine gtk2-engines-pixbuf hunspell-fr kaisen-mate kaisen-menu kaisen-skeleton libatrildocument3 \
        libatrilview3 libaudclient2 libcaja-extension1 libcpupower1 libexempi8 libffmpegthumbnailer4v5 libgail-3-0 \
        libgtk-layer-shell0 libgtksourceview-3.0-1 libgtksourceview-3.0-common libgucharmap-2-90-7 libid3tag0 libimlib2 \
        libjs-mathjax liblightdm-gobject-1-0 liblua5.1-0 libmarco-private2 libmate-desktop-2-17 libmate-menu2 \
        libmate-panel-applet-4-1 libmate-slab0 libmate-window-settings1 libmatedict6 libmatekbd-common libmatekbd4 \
        libmatemixer-common libmatemixer0 libmateweather-common libmateweather1 libndp0 libnma-common libnma0 libpeas-1.0-0 \
        libpeas-common librda-common librda0 libteamdctl0 libwnck-3-0 libwnck-3-common libxklavier16 libxmmsclient6 \
        libxpresent1 lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings marco marco-common mate-applet-brisk-menu \
        mate-applets mate-applets-common mate-backgrounds mate-calc mate-calc-common mate-control-center \
        mate-control-center-common mate-desktop mate-desktop-common mate-desktop-environment mate-desktop-environment-core \
        mate-icon-theme mate-media mate-media-common mate-menus mate-notification-daemon mate-notification-daemon-common \
        mate-panel mate-panel-common mate-polkit mate-polkit-common mate-power-manager mate-power-manager-common \
        mate-screensaver mate-screensaver-common mate-session-manager mate-settings-daemon mate-settings-daemon-common \
        mate-system-monitor mate-system-monitor-common mate-terminal mate-terminal-common mate-themes mate-user-guide \
        mate-utils mate-utils-common menu-xdg mobile-broadband-provider-info network-manager network-manager-gnome pluma \
        pluma-common python-configparser python-entrypoints python-keyring xcursor-themes zenity zenity-common && \
	apt install -y kaisen-xfce || true && apt -y --fix-broken install && apt -y autoremove
	#If rollback on XFCE, reapplying XFCE users configurations or reapplying default XFCE configurations
        for users in $(awk -F: '/\/home/ && ($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
        do
        cp -rp /usr/share/kaisen-interface-switcher/$users/XFCE/* /home/$users/.config/ 2> /dev/null || cp -rf /etc/skel/.config/{xfce4,gtkrc,gtkrc-2.0,gtk-2.0,gtk-3.0} /home/$users/.config/ 2> /dev/null || true
        done
        if [[ "$DESKTOP_SESSION" -eq "lightdm-xsession" ]]; then
                systemctl restart lightdm
        else
                /sbin/reboot
        fi
fi

if [[ $OPTION = "4" ]]; then
	exit 0
fi
fi
